apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: posmon
  namespace: posmon
spec:
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-posmon
  namespace: posmon
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30903
    port: 9093
    protocol: TCP
    targetPort: web
  selector:
    alertmanager: posmon
