apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alertmanager-gotify
  name: alertmanager-gotify
  namespace: posmon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager-gotify
  template:
    metadata:
      labels:
        app: alertmanager-gotify
    spec:
      containers:
      - image: r.sbruder.de/alertmanager-gotify:latest
        name: alertmanager-gotify
        env:
        - name: GOTIFY_URL
          value: https://gotify.tbrnt.ch
        ports:
        - containerPort: 8081
          name: web
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-gotify
  namespace: posmon
spec:
  ports:
  - name: web
    port: 8081
    protocol: TCP
    targetPort: web
  selector:
    app: alertmanager-gotify
  type: ClusterIP
