apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: iotbox
  name: iotbox
  namespace: pos
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: iotbox
  template:
    metadata:
      labels:
        app: iotbox
    spec:
      containers:
      - args:
        - --
        - --load=web,hw_proxy,hw_posbox_homepage,hw_posbox_upgrade,hw_scale,hw_scanner,hw_escpos,hw_blackbox_be,hw_screen,hw_drivers,hw_printer_network
        env:
        - name: HOST
          value: db
        - name: PASSWORD
          value: odoo
        - name: USER
          value: odoo
        image: docker.io/tobru/odoo-pos:latest-iotbox
        imagePullPolicy: Always
        name: iotbox
        ports:
        - name: http
          containerPort: 8069
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 300
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
      hostname: iotbox
      restartPolicy: Always
